export const FETCH_LOCATION_BY_IP_START = 'LOCATION/FETCH_LOCATION_BY_IP_START'

export const FETCH_LOCATION_BY_IP_SUCCESS =
  'LOCATION/FETCH_LOCATION_BY_IP_SUCCESS'

export const FETCH_LOCATION_BY_IP_FAILURE =
  'LOCATION/FETCH_LOCATION_BY_IP_FAILURE'