export const FETCH_LOCATION_BY_INPUT_START =
  'LOCATION/FETCH_LOCATION_BY_INPUT_START'

export const FETCH_LOCATION_BY_INPUT_SUCCESS =
  'LOCATION/FETCH_LOCATION_BY_INPUT_SUCCESS'

export const FETCH_LOCATION_BY_INPUT_FAILURE =
  'LOCATION/FETCH_LOCATION_BY_INPUT_FAILURE'