export const FETCH_REAL_TIME_WEATHER_START =
  'WEATHER/FETCH_REAL_TIME_WEATHER_START'

export const FETCH_REAL_TIME_WEATHER_SUCCESS =
  'WEATHER/FETCH_REAL_TIME_WEATHER_SUCCESS'

export const FETCH_REAL_TIME_WEATHER_FAILURE =
  'WEATHER/FETCH_REAL_TIME_WEATHER_FAILURE'

// 更新预测天气

export const FETCH_WEATHER_FORECAST_START =
  'WEATHER/FETCH_WEATHER_FORECAST_START'

export const FETCH_WEATHER_FORECAST_SUCCESS =
  'WEATHER/FETCH_WEATHER_FORECAST_SUCCESS'

export const FETCH_WEATHER_FORECAST_FAILURE =
  'WEATHER/FETCH_WEATHER_FORECAST_FAILURE'